services:
  - type: web
    name: outlook-zip-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CLIENT_ID
        value: ${CLIENT_ID}  # Reference environment variable
      - key: CLIENT_SECRET
        value: ${CLIENT_SECRET}  # Reference environment variable
      - key: TENANT_ID
        value: ${TENANT_ID}  # Reference environment variable
      - key: USER_EMAIL
        value: ${USER_EMAIL}  # Reference environment variable
